#This file was generated on 15 October 2019

name: letsquiz
description: Trivia Quiz Built Using Flutter

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  #Flutter package to use SVG images in the project
  flutter_svg: ^0.14.4

  #Flutter package to launch URLs
  url_launcher: ^5.1.2

  # Flutter package for gradient appbar.
  gradient_app_bar: ^0.1.3

  # Flutter package for icons (by Font Awesome).
  font_awesome_flutter: ^8.4.0

  # Flutter package for making http requests.
  http: ^0.12.0+2

  # Flutter package that provides you custom clippers to help you achieve various custom shapes.
  flutter_custom_clippers: ^0.1.6 
  
  # A Dart library for unescaping HTML-encoded strings. 
  html_unescape: ^1.0.1+2

  # Flutter widget that automatically resizes text to fit perfectly within its bounds.
  auto_size_text: ^2.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - assets/images/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Bold.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300